### ISSUE TITLE
Missing _testcapi

### ISSUE THREAD

**Issue by Super99Master** [astral-sh/python-build-standalone#202]
Is build/run_tests.py reliable?

i keep getting "No module named '_testcapi'"

Tested with version:
3.9.16 | cpython-3.9.16+20230507-x86_64_v2-unknown-linux-gnu-debug-full
3.9.17 | cpython-3.9.17+20230726-x86_64-unknown-linux-gnu-pgo+lto-full
3.9.18 | cpython-3.9.18+20231002-x86_64-unknown-linux-gnu-pgo+lto-full
3.11.6 | cpython-3.11.6+20231002-x86_64-unknown-linux-gnu-pgo+lto-full
3.12.0 | cpython-3.12.0+20231002-x86_64-unknown-linux-gnu-pgo+lto-full
            | cpython-3.12.0+20231002-x86_64-unknown-linux-gnu-debug-full

#15 is the only issue with _testcapi but doesn't look like it has a solution

**Comment by indygreg** [comment]
`build/run_tests.py` does have some expected failures because our build methodology is different from official builds. I just haven't put in effort to patch failing tests or send workarounds upstream.

`_testcapi` is disabled because it is only used for tests and doesn't play well with our _extensions are static_ philosophy. I can't remember details other than I believe it has been disabled for ages because of the hardship it creates.
