### ISSUE TITLE
Remove pgo builds when pgo+lto builds exist

### ISSUE THREAD

**Issue by zanieb** [astral-sh/python-build-standalone#442]
In the style of https://github.com/astral-sh/python-build-standalone/pull/223 — is there a downside to this?

It'd be nice to reduce the matrix if these aren't providing value.

**Comment by indygreg** [comment]
Historically I kept the non-LTO variants for PyOxidizer support for... reasons.

You have my permission to remove PGO when PGO+LTO exists.

**Comment by zanieb** [comment]
> for... reasons.

👀 

Thanks for confirming!

**Comment by ntamas** [comment]
@indygreg @zanieb Will the PGO+LTO builds work with PyOxidizer as-is?

(Background: I have been trying to keep PyOxidizer alive for the last few months in my fork (see https://github.com/ntamas/PyOxidizer) because I need it for my own projects and I've mostly gotten it to work (apart from the musl libc builds) with recent versions of PyO3 and everything. I'm currently in the process of updating the corresponding Python distributions).
